### PR TITLE
Use composer API instead of checking explicit paths

### PR DESCRIPTION
**Pull request by rbayliss**
Hey!
This is a proposal to switch away from using explicit paths to using Composer's APIs to find console extensions.  I'm fairly sure this PR is half baked and broken at the moment, because I don't fully understand the functionality this package provides, but I wanted to throw it out there and see if there's interest in doing it this way.  If there is, I can do some testing to make sure it works as expected. 

This is a followup to #2.

### CODE REVIEW

**Comment by jmolivas** [comment]
Thanks for the PR, and sorry for the delay I will review this this week.

**Comment by jmolivas** [comment]
@rbayliss Thanks for the PR, and sorry for the delay I will review this this week before DrupalCon.

**Comment by mike-potter** [comment]
+1 to this.  It fixes the performance issue that I raised in issue #6

**Comment by mike-potter** [comment]
Since processProjectPackages() in ExtenderManager.php is no longer called, do we still need that function and it's related code?

**Comment by jmolivas** [comment]
@rbayliss Thanks for your contribution, your PR was merged. This will be included on the next release.

**Pull request merged**
