### PR TITLE
Fix include path in Extender.php

### PR DESCRIPTION
**Pull request by webflo**
Quickfix for https://github.com/hechoendrupal/drupal-console-extend-plugin/issues/2 and https://github.com/drupal-composer/drupal-project/issues/269

### CODE REVIEW

**Comment by rbayliss** [comment]
Makes sense to me.

**Comment by mtodor** [comment]
I have also checked this and it works good for me too.

**Comment by jmolivas** [comment]
Yes this seems to fix the issue

**Comment by pfrenssen** [comment]
Make a new release with this fix?

**Comment by jmolivas** [comment]
New released tagged https://github.com/hechoendrupal/drupal-console-extend-plugin/releases/tag/0.6.0

**Comment by jmolivas** [comment]
@webflo Thanks for your contribution.

**Pull request merged**
